channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.3
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.15.2
name: mlflow-env
